name: sentryhooks
description: Sending Sentry Hooks to Telegram messages
version: 0.0.1
# homepage: https://www.example.com
publish_to: 'none'

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  meta: ^1.7.0
  http: ^0.13.3
  functions_framework: ^0.4.1
  shelf: ^1.2.0
  #gcloud: ^0.7.3

dev_dependencies:
  build_runner: ^2.0.6
  build_verify: ^2.0.0
  functions_framework_builder: ^0.4.3

  pedantic: ^1.11.1

  test: ^1.17.10
  test_process: ^2.0.2
  mockito: ^5.0.12
